### ISSUE TITLE
Unable to generate a new app

### ISSUE THREAD

**Issue by gk-bbai** [hogarthww-labs/nx-python#2]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

After selecting which python framework I would like to use for the application (I select "default"), I get an error:

```bash
➜ nx g @nx-python/nx-python:nx-python --name=my-project --verbose

 NX  Generating @nx-python/nx-python:nx-python

✔ Which python framework would you like to use for the application? · default
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/user/Projects/my-project/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/validate/index.js:464:13)
    at /Users/user/Projects/my-project/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/user/Projects/my-project/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/user/Projects/my-project/node_modules/ajv/dist/compile/codegen/index.js:568:18)

 NX   NOT SUPPORTED: keyword "id", use "$id" for schema ID
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1. `npm i -D @nx-python/nx-python`
2. `nx g @nx-python/nx-python:nx-python --name=my-project`
3. Select "default" for the python framework to use

* **What is the expected behavior?**

No error.

* **What is the motivation / use case for changing the behavior?**

Plugin isn't able to generate new applications.

* **Please tell us about your environment:**
  
  - Version: nx v18.2.4,  @nx-python/nx-python v1.0.3
  - Browser: N/A
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by aliframdani-jbl** [comment]
the mfs doesn't even active coding again since 4 years ago bro. Don't use this unless you want to update it by yourself by forking or etc
